// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSessions():Promise<Array<main.SessionInfo>>;

export function ResetAlerts():Promise<void>;
